name: flutter_screen_recorder_ffmpeg
description: This is an experimental package that provides a simple way to render widget to video/gif using ffmpeg (it is not the best way but by the moment is the best method)
version: 0.0.4
homepage: https://github.com/camilo1498/flutter_widget_recorder_ffmpeg

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^3.0.2
  path_provider: ^2.0.8
  ffmpeg_kit_flutter_min_gpl: ^4.5.1
  permission_handler: ^8.1.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:

